SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `rs_karma` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `MapId` mediumint(9) NOT NULL DEFAULT '0',
  `PlayerId` mediumint(9) NOT NULL DEFAULT '0',
  `Score` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `PlayerMapId` (`PlayerId`,`MapId`),
  KEY `MapId` (`MapId`),
  KEY `Score` (`Score`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;



CREATE TABLE IF NOT EXISTS `rs_rank` (
  `PlayerId` mediumint(9) NOT NULL DEFAULT '0',
  `Avg` float NOT NULL DEFAULT '0',
  KEY `PlayerId` (`PlayerId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `rs_times` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `MapId` mediumint(9) NOT NULL DEFAULT '0',
  `PlayerId` mediumint(9) NOT NULL DEFAULT '0',
  `Score` int(11) NOT NULL DEFAULT '0',
  `Date` int(10) unsigned NOT NULL DEFAULT '0',
  `Checkpoints` text NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `PlayerMapId` (`PlayerId`,`MapId`),
  KEY `MapId` (`MapId`),
  KEY `Score` (`Score`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
